"""Initial migration.

Revision ID: 853345893903
Revises: 
Create Date: 2024-09-24 21:39:23.441201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853345893903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('sender_id')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
